export interface Course {
  trilha: string
  titulo: string
  sinopse: string
  link: string
}

export const COURSES: Course[] = [
  {
    trilha: "Biblioteca de Automa\u00e7\u00f5es",
    titulo: "Introdu\u00e7\u00e3o",
    sinopse: "Apresenta\u00e7\u00e3o do curso e vis\u00e3o geral das automa\u00e7\u00f5es com n8n para gestores de tr\u00e1fego pago.",
    link: "https://app.agenze.io/c/automacoes-aplicadas-a-gestao-de-trafego/sections/895640/lessons/3392517",
  },
  {
    trilha: "Biblioteca de Automa\u00e7\u00f5es",
    titulo: "Aula 2",
    sinopse: "Aprofundamento em ferramentas e fluxos de automa\u00e7\u00e3o no n8n aplicados \u00e0 gest\u00e3o de tr\u00e1fego.",
    link: "https://app.agenze.io/c/automacoes-aplicadas-a-gestao-de-trafego/sections/895640/lessons/3392522",
  },
  {
    trilha: "Biblioteca de Automa\u00e7\u00f5es",
    titulo: "Aula 3",
    sinopse: "T\u00e9cnicas avan\u00e7adas de automa\u00e7\u00e3o para otimizar a rotina operacional do gestor de tr\u00e1fego.",
    link: "https://app.agenze.io/c/automacoes-aplicadas-a-gestao-de-trafego/sections/895640/lessons/3392532",
  },
  {
    trilha: "Biblioteca de Automa\u00e7\u00f5es",
    titulo: "Domine o Fluxo de Vendas: Importando e Analisando o Template de Agente Aut\u00f4nomo para WhatsApp (n8n)",
    sinopse: "Como importar e configurar o agente aut\u00f4nomo de vendas no n8n integrado ao WhatsApp.",
    link: "https://app.agenze.io/c/automacoes-aplicadas-a-gestao-de-trafego/sections/895640/lessons/3392537",
  },
  {
    trilha: "Biblioteca de Automa\u00e7\u00f5es",
    titulo: "Monitor de Campanhas Meta - WhatsApp",
    sinopse: "Automa\u00e7\u00e3o que monitora campanhas do Meta ADS e dispara alertas em tempo real pelo WhatsApp.",
    link: "https://app.agenze.io/c/automacoes-aplicadas-a-gestao-de-trafego/sections/895640/lessons/3392540",
  },
  {
    trilha: "Biblioteca de Automa\u00e7\u00f5es",
    titulo: "Relat\u00f3rio Inteligente do Meta (Facebook) Ads",
    sinopse: "Cria\u00e7\u00e3o de relat\u00f3rio automatizado com dados e insights das campanhas do Meta (Facebook) Ads.",
    link: "https://app.agenze.io/c/automacoes-aplicadas-a-gestao-de-trafego/sections/895640/lessons/3392543",
  },
  {
    trilha: "Biblioteca de Automa\u00e7\u00f5es",
    titulo: "Monitor Autom\u00e1tico de Saldo do Meta Ads",
    sinopse: "Automa\u00e7\u00e3o que monitora e alerta sobre o saldo dispon\u00edvel nas contas de an\u00fancio do Meta Ads.",
    link: "https://app.agenze.io/c/automacoes-aplicadas-a-gestao-de-trafego/sections/895640/lessons/3392550",
  },
  {
    trilha: "Agentes de IA",
    titulo: "Analista de P\u00e1gina de Vendas",
    sinopse: "Agente de IA que analisa p\u00e1ginas de vendas e aponta melhorias para aumentar a convers\u00e3o.",
    link: "https://app.agenze.io/c/agentes-de-ia-para-gestao-de-trafego/sections/895648/lessons/3395377",
  },
  {
    trilha: "Agentes de IA",
    titulo: "Auditor de Performance Digital",
    sinopse: "Agente que realiza auditoria completa de m\u00e9tricas e performance de campanhas digitais.",
    link: "https://app.agenze.io/c/agentes-de-ia-para-gestao-de-trafego/sections/895648/lessons/3395378",
  },
  {
    trilha: "Agentes de IA",
    titulo: "Agente Otimizador de ROI de Campanhas",
    sinopse: "IA que analisa dados de campanhas e sugere otimiza\u00e7\u00f5es pr\u00e1ticas para maximizar o ROI.",
    link: "https://app.agenze.io/c/agentes-de-ia-para-gestao-de-trafego/sections/895648/lessons/3395390",
  },
  {
    trilha: "Agentes de IA",
    titulo: "Agente Atendimento ao Cliente",
    sinopse: "Agente de IA para automatizar e escalar o atendimento ao cliente com consist\u00eancia e qualidade.",
    link: "https://app.agenze.io/c/agentes-de-ia-para-gestao-de-trafego/sections/895648/lessons/3395394",
  },
  {
    trilha: "Agentes de IA",
    titulo: "Agente Gerador de ATA de Reuni\u00f5es",
    sinopse: "IA que transcreve reuni\u00f5es automaticamente e gera ATAs formatadas em segundos.",
    link: "https://app.agenze.io/c/agentes-de-ia-para-gestao-de-trafego/sections/895648/lessons/3395400",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Instalando n8n / Evolution API",
    sinopse: "Passo a passo para instalar e configurar o n8n e a Evolution API em seu servidor.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395311",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Importando o Template",
    sinopse: "Como importar corretamente o template do M\u00e1quina de Reuni\u00f5es no n8n.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395291",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Credencial - OpenAI",
    sinopse: "Como criar e integrar as credenciais da OpenAI no n8n para usar modelos de linguagem.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395289",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Credencial - APIFY",
    sinopse: "Como configurar e conectar as credenciais do APIFY ao fluxo do n8n.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395328",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Credencial - Redis",
    sinopse: "Configura\u00e7\u00e3o do Redis como banco de dados de mem\u00f3ria para os agentes de IA no n8n.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395286",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Credencial / Banco de Dados - Supabase",
    sinopse: "Integra\u00e7\u00e3o do Supabase como banco de dados principal no fluxo do M\u00e1quina de Reuni\u00f5es.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395281",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Credenciais - Google",
    sinopse: "Configura\u00e7\u00e3o das APIs e credenciais do Google (Drive, Calendar) para uso no n8n.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395277",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Review do Fluxo",
    sinopse: "Revis\u00e3o detalhada de cada n\u00f3 do fluxo do M\u00e1quina de Reuni\u00f5es e suas fun\u00e7\u00f5es.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395298",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Conectar ao Review do Fluxo",
    sinopse: "Como conectar e validar a integra\u00e7\u00e3o do fluxo com todos os servi\u00e7os configurados.",
    link: "https://app.agenze.io/c/aulas/sections/896260/lessons/3395321",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Acesse o Checklist",
    sinopse: "Checklist completo de configura\u00e7\u00f5es e valida\u00e7\u00f5es necess\u00e1rias para o sistema funcionar.",
    link: "https://app.agenze.io/c/aulas/sections/898178/lessons/3402635",
  },
  {
    trilha: "Aulas Complementares do M\u00e1quina de Reuni\u00f5es",
    titulo: "Implementa\u00e7\u00e3o Guiada 05/03",
    sinopse: "Grava\u00e7\u00e3o da sess\u00e3o de implementa\u00e7\u00e3o ao vivo com suporte e resolu\u00e7\u00e3o de d\u00favidas em tempo real.",
    link: "https://app.agenze.io/c/aulas/sections/926074/lessons/3560720",
  },
  {
    trilha: "Replay M\u00e1quina de Reuni\u00f5es ao Vivo",
    titulo: "Assista a Grava\u00e7\u00e3o aqui 02:39:35",
    sinopse: "Grava\u00e7\u00e3o completa (2h39) do evento ao vivo de lan\u00e7amento do M\u00e1quina de Reuni\u00f5es.",
    link: "https://app.agenze.io/c/replay-maquina-de-reunioes-ao-vivo/sections/899722/lessons/3408117",
  },
  {
    trilha: "Template e Materiais",
    titulo: "Baixe o Template Aqui",
    sinopse: "Download do template principal do M\u00e1quina de Reuni\u00f5es para importar no n8n.",
    link: "https://app.agenze.io/c/template-e-materiais/sections/898184/lessons/3402663",
  },
  {
    trilha: "Template e Materiais",
    titulo: "Acesse o Checklist",
    sinopse: "Checklist de recursos e tarefas de apoio para a implementa\u00e7\u00e3o completa do sistema.",
    link: "https://app.agenze.io/c/template-e-materiais/sections/898186/lessons/3402671",
  },
  {
    trilha: "Trilha Pinterest ADS",
    titulo: "Anunciando no Pinterest com ROI de 20x",
    sinopse: "Estrat\u00e9gias e configura\u00e7\u00f5es para criar campanhas lucrativas no Pinterest Ads com ROI de 20x.",
    link: "https://app.agenze.io/c/trilha-pinterest/sections/911704/lessons/3453937",
  },
  {
    trilha: "Trilha Pinterest ADS",
    titulo: "Aula B\u00f4nus: Como trabalhar o branding no Pinterest para vender mais",
    sinopse: "Como usar branding e conte\u00fado no Pinterest para potencializar o alcance e as vendas.",
    link: "https://app.agenze.io/c/trilha-pinterest/sections/911704/lessons/3453962",
  },
  {
    trilha: "Escala de Ag\u00eancia",
    titulo: "Como Estruturar Planos, Trilhas e Comissionamento",
    sinopse: "Modelo de planos de carreira, trilhas de crescimento e comissionamento para equipes de ag\u00eancia.",
    link: "https://app.agenze.io/c/escala-de-agencia/sections/925403/lessons/3507360",
  },
  {
    trilha: "Trilha Sucesso do Cliente",
    titulo: "Gest\u00e3o de Crise - atendimento, reten\u00e7\u00e3o e LTV",
    sinopse: "T\u00e9cnicas para gerenciar crises, reter clientes insatisfeitos e aumentar o LTV da base.",
    link: "https://app.agenze.io/c/trilha-sucesso-do-cliente/sections/926161/lessons/3511442",
  },
  {
    trilha: "Trilha Sucesso do Cliente",
    titulo: "Passagem de Bast\u00e3o Comercial --> Operacional (+ Onboarding com Cliente)",
    sinopse: "Como estruturar a passagem do comercial para o operacional com onboarding eficiente do cliente.",
    link: "https://app.agenze.io/c/trilha-sucesso-do-cliente/sections/926161/lessons/3511466",
  },
  {
    trilha: "Trilha Monetiza\u00e7\u00e3o da Base",
    titulo: "Aumentando Ticket com Servi\u00e7o de SEO",
    sinopse: "Como oferecer SEO como servi\u00e7o complementar para aumentar o ticket m\u00e9dio com clientes atuais.",
    link: "https://app.agenze.io/c/trilha-monetizacao-da-base-dd0850/sections/924431/lessons/3503730",
  },
  {
    trilha: "Trilha Meta Andromeda",
    titulo: "O que \u00e9 e como funciona o Andromeda",
    sinopse: "Apresenta\u00e7\u00e3o do M\u00e9todo Andr\u00f4meda: conceito, l\u00f3gica e aplica\u00e7\u00e3o pr\u00e1tica no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-andromeda/sections/886790/lessons/3453965",
  },
  {
    trilha: "Trilha Meta Andromeda",
    titulo: "M\u00e9todo Andr\u00f4meda",
    sinopse: "Implementa\u00e7\u00e3o completa do M\u00e9todo Andr\u00f4meda para escalar resultados nas campanhas do Meta.",
    link: "https://app.agenze.io/c/trilha-meta-andromeda/sections/886790/lessons/3536935",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Agentes GPT aplicados \u00e0 Gest\u00e3o de Tr\u00e1fego",
    sinopse: "Como usar agentes GPT para automatizar an\u00e1lises e otimiza\u00e7\u00f5es de campanhas de tr\u00e1fego.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358240",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Aul\u00e3o Estrat\u00e9gico Tr\u00e1fego com IA",
    sinopse: "Aula estrat\u00e9gica completa sobre como potencializar tr\u00e1fego pago com intelig\u00eancia artificial.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358242",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Como Transformo uma Reuni\u00e3o em Uma Proposta Irresist\u00edvel em 30 Minutos",
    sinopse: "M\u00e9todo para transformar reuni\u00f5es em propostas comerciais irresist\u00edveis usando IA em 30 min.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358244",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Criativos para An\u00fancios com IA",
    sinopse: "Como criar e otimizar criativos para an\u00fancios usando ferramentas de intelig\u00eancia artificial.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358247",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Gera\u00e7\u00e3o de Criativos com IA - (com Bruno Gabarra)",
    sinopse: "Workshop com especialista sobre gera\u00e7\u00e3o de criativos de alta convers\u00e3o usando IA.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358250",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "IA para Grava\u00e7\u00e3o e Transcri\u00e7\u00e3o de Reuni\u00f5es + Playbook de ATA",
    sinopse: "Ferramentas de IA para gravar, transcrever reuni\u00f5es e gerar ATAs profissionais automaticamente.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358252",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Introdu\u00e7\u00e3o",
    sinopse: "Vis\u00e3o geral da Trilha Ag\u00eancia Automatizada e o que ser\u00e1 abordado em cada m\u00f3dulo.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358256",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Modelo Ideal de IA no ChatGPT",
    sinopse: "Como configurar o modelo ideal de IA no ChatGPT para uso na gest\u00e3o de tr\u00e1fego.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358260",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Os 4 Pilares da Gest\u00e3o de Tr\u00e1fego com IA",
    sinopse: "Os quatro fundamentos para integrar IA de forma eficaz na rotina de gest\u00e3o de tr\u00e1fego pago.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358262",
  },
  {
    trilha: "Trilha Ag\u00eancia Automatizada",
    titulo: "Otimiza\u00e7\u00e3o de Campanha na Pr\u00e1tica com IA",
    sinopse: "Processo pr\u00e1tico de otimiza\u00e7\u00e3o de campanhas com suporte de an\u00e1lise por intelig\u00eancia artificial.",
    link: "https://app.agenze.io/c/trilha-ia-aplicada-a-gestao-de-trafego/sections/886781/lessons/3358264",
  },
  {
    trilha: "Trilha Aquisi\u00e7\u00e3o de Clientes",
    titulo: "Funil Social Selling (com Aluno Matheus Foletto)",
    sinopse: "Caso real: como usar social selling para fechar clientes de gest\u00e3o de tr\u00e1fego do zero.",
    link: "https://app.agenze.io/c/trilha-aquisicao-de-clientes/sections/926104/lessons/3511140",
  },
  {
    trilha: "Trilha Aquisi\u00e7\u00e3o de Clientes",
    titulo: "De 9k para 80k/m\u00eas em 2 anos (com aluno Gabriel Werneck)",
    sinopse: "Jornada de crescimento de R$9k para R$80k/m\u00eas em 2 anos com estrat\u00e9gias de aquisi\u00e7\u00e3o.",
    link: "https://app.agenze.io/c/trilha-aquisicao-de-clientes/sections/926104/lessons/3511392",
  },
  {
    trilha: "Trilha Aquisi\u00e7\u00e3o de Clientes",
    titulo: "Social Selling na Opera\u00e7\u00e3o \u2014 Como vender mais, gastando menos",
    sinopse: "Como implementar social selling na opera\u00e7\u00e3o para vender mais gastando menos.",
    link: "https://app.agenze.io/c/trilha-aquisicao-de-clientes/sections/926104/lessons/3511402",
  },
  {
    trilha: "Trilha Conceitos e Pilares do Marketing Digital",
    titulo: "Gloss\u00e1rio do Marketing Digital",
    sinopse: "Defini\u00e7\u00f5es dos principais termos e conceitos utilizados no marketing digital.",
    link: "https://app.agenze.io/c/trilha-conceitos-e-pilares-do-marketing-digital/sections/886756/lessons/3358161",
  },
  {
    trilha: "Trilha Conceitos e Pilares do Marketing Digital",
    titulo: "Marketing Digital n\u00e3o \u00e9 Tr\u00e1fego Pago",
    sinopse: "Vis\u00e3o ampla do marketing digital e como o tr\u00e1fego pago se encaixa no ecossistema.",
    link: "https://app.agenze.io/c/trilha-conceitos-e-pilares-do-marketing-digital/sections/886756/lessons/3358170",
  },
  {
    trilha: "Trilha Conceitos e Pilares do Marketing Digital",
    titulo: "O que \u00e9 Traqueamento",
    sinopse: "Conceito e import\u00e2ncia do rastreamento de convers\u00f5es para otimizar campanhas digitais.",
    link: "https://app.agenze.io/c/trilha-conceitos-e-pilares-do-marketing-digital/sections/886756/lessons/3358172",
  },
  {
    trilha: "Trilha Conceitos e Pilares do Marketing Digital",
    titulo: "O que s\u00e3o M\u00e9tricas",
    sinopse: "As principais m\u00e9tricas do marketing digital e como interpret\u00e1-las para decis\u00f5es assertivas.",
    link: "https://app.agenze.io/c/trilha-conceitos-e-pilares-do-marketing-digital/sections/886756/lessons/3358174",
  },
  {
    trilha: "Trilha Conceitos e Pilares do Marketing Digital",
    titulo: "Quais Fontes de Tr\u00e1fego Existem e por Onde Come\u00e7ar",
    sinopse: "Panorama das fontes de tr\u00e1fego dispon\u00edveis e crit\u00e9rios para escolher por onde come\u00e7ar.",
    link: "https://app.agenze.io/c/trilha-conceitos-e-pilares-do-marketing-digital/sections/886756/lessons/3358178",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "Big Idea",
    sinopse: "Como encontrar e desenvolver a grande ideia central que torna um an\u00fancio irresist\u00edvel.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358114",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "C\u00e9rebro Trino",
    sinopse: "Como o neuromarketing e o c\u00e9rebro trino influenciam a decis\u00e3o de compra do consumidor.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358119",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "Fear x Greed",
    sinopse: "Como usar medo e gan\u00e2ncia como gatilhos emocionais para aumentar convers\u00e3o em an\u00fancios.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358122",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "Funil x Marketing Direto",
    sinopse: "Diferen\u00e7as e aplica\u00e7\u00f5es do funil de vendas versus marketing direto em an\u00fancios pagos.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358127",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "Gatilhos Mentais",
    sinopse: "Os principais gatilhos mentais e como aplic\u00e1-los em copies de an\u00fancios para vender mais.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358133",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "Headlines Matadoras",
    sinopse: "T\u00e9cnicas para criar t\u00edtulos e manchetes que capturam aten\u00e7\u00e3o e geram cliques nos an\u00fancios.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358137",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "Mecanismo \u00danico",
    sinopse: "Como criar e comunicar um diferencial \u00fanico que posiciona sua oferta acima da concorr\u00eancia.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358143",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "N\u00edveis de Consci\u00eancia",
    sinopse: "Como adaptar a copy para cada n\u00edvel de consci\u00eancia do p\u00fablico-alvo e aumentar convers\u00f5es.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358145",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "O que \u00e9 copywriting",
    sinopse: "Fundamentos do copywriting e sua import\u00e2ncia na cria\u00e7\u00e3o de an\u00fancios persuasivos e eficazes.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358147",
  },
  {
    trilha: "Trilha Copy Persuasiva para an\u00fancios vencedores",
    titulo: "Quebra de Obje\u00e7\u00f5es",
    sinopse: "T\u00e9cnicas para antecipar e neutralizar as principais obje\u00e7\u00f5es do cliente dentro do an\u00fancio.",
    link: "https://app.agenze.io/c/trilha-copy-persuasiva-para-anuncios-vencedores/sections/886733/lessons/3358149",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Introdu\u00e7\u00e3o aos GPTs - O que s\u00e3o e como Utiliz\u00e1-los.",
    sinopse: "Conceito de GPTs personalizados e como criar e usar agentes de IA no ChatGPT.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358053",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "\u00c1rvore de Pensamentos (ToT) Expans\u00e3o de Ideias em Prompt",
    sinopse: "T\u00e9cnica Tree of Thought para criar prompts que expandem e exploram ideias complexas.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358056",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Cadeia de Pensamento (CoT) Estimulando Respostas Elaboradas",
    sinopse: "Como usar Chain of Thought para induzir a IA a raciocinar passo a passo nas respostas.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358061",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Como Estruturar Prompts Eficazes para GPTs",
    sinopse: "Estrutura e boas pr\u00e1ticas para criar prompts que geram resultados consistentes e precisos.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358070",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Compreendendo Tokens",
    sinopse: "O que s\u00e3o tokens, como funcionam e como otimizar seu uso para melhores resultados na IA.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358072",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Configurando seu GPT Passo a Passo",
    sinopse: "Tutorial completo para criar, configurar e publicar um GPT personalizado no ChatGPT.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358075",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Fundamentos da Engenharia de Prompt",
    sinopse: "Princ\u00edpios b\u00e1sicos da engenharia de prompt para maximizar a qualidade das respostas da IA.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358077",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Instru\u00e7\u00f5es Personalizadas vs GPTs",
    sinopse: "Quando usar instru\u00e7\u00f5es personalizadas e quando criar um GPT customizado para cada tarefa.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358081",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Marketing Digital Moderno",
    sinopse: "Como aplicar IA e engenharia de prompt nas estrat\u00e9gias de marketing digital moderno.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358084",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "O que \u00e9 IA",
    sinopse: "Conceitos fundamentais de intelig\u00eancia artificial e como ela funciona de forma acess\u00edvel.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358088",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Termos Essenciais da Engenharia de Prompt",
    sinopse: "Gloss\u00e1rio dos termos essenciais para quem quer dominar a engenharia de prompt.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358092",
  },
  {
    trilha: "Trilha Engenharia de Prompt com Head de IA da Ag\u00eancia Rei",
    titulo: "Zero-Shot e Few-Shot",
    sinopse: "T\u00e9cnicas zero-shot e few-shot learning para obter melhores respostas com ou sem exemplos.",
    link: "https://app.agenze.io/c/trilha-engenharia-de-prompt-com-head-de-ia-da-agencia-rei/sections/886717/lessons/3358100",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Aquecendo sua Conta de An\u00fancio e Motivos que podem te Bloquear no Facebook ADS",
    sinopse: "Como aquecer uma conta nova e evitar os principais motivos de bloqueio no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3357981",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Como Criar um Cat\u00e1logo de Produtos no Facebook",
    sinopse: "Passo a passo para criar e configurar cat\u00e1logos de produtos no Gerenciador do Meta.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3357987",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Como Fazer Tr\u00e1fego em 2026",
    sinopse: "Panorama das melhores estrat\u00e9gias e abordagens para tr\u00e1fego pago em 2026.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3357992",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Como o seu Cliente compartilha acesso aos ativos com voc\u00ea",
    sinopse: "Tutorial de como receber acesso a contas, p\u00e1ginas, pixels e cat\u00e1logos de clientes no Meta.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3357995",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Conferindo o Rastreamento de Eventos",
    sinopse: "Como verificar e validar se os eventos de convers\u00e3o est\u00e3o sendo rastreados corretamente.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358001",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Conting\u00eancia para Evitar dor de Cabe\u00e7a",
    sinopse: "Estrat\u00e9gias e backups essenciais para evitar crises com bloqueios na conta de an\u00fancio.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358005",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Cria\u00e7\u00e3o de Perfil e BM no Meta (Facebook) ADS",
    sinopse: "Como criar perfil pessoal e Business Manager corretamente no Meta para gest\u00e3o de clientes.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358010",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Cria\u00e7\u00e3o e Acesso de P\u00e1gina no Facebook",
    sinopse: "Como criar e gerenciar p\u00e1ginas no Facebook para uso em campanhas de an\u00fancios pagos.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358015",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Links \u00dateis para Falar Diretamente com o Suporte do Facebook",
    sinopse: "Compilado de links diretos para contato com o suporte do Meta em diferentes situa\u00e7\u00f5es.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358019",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Mapa Mental Estrutura do Meta (Facebook ADS)",
    sinopse: "Mapa visual completo da estrutura do Gerenciador de An\u00fancios do Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358023",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Os 3 N\u00edveis de uma Conta de An\u00fancio",
    sinopse: "Entendendo os tr\u00eas n\u00edveis: campanha, conjunto de an\u00fancios e an\u00fancio no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358026",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Passo a Passo para Criar o Pixel do Facebook",
    sinopse: "Como criar, instalar e configurar o Pixel do Meta para rastrear convers\u00f5es com precis\u00e3o.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358029",
  },
  {
    trilha: "Trilha Meta ADS (Facebook ADS) - O In\u00edcio",
    titulo: "Passo a Passo para Criar sua Primeira Conta de An\u00fancio",
    sinopse: "Tutorial completo para criar e configurar do zero uma conta de an\u00fancio no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads-facebook-ads-o-inicio/sections/886702/lessons/3358035",
  },
  {
    trilha: "Trilha Google ADS",
    titulo: "80/20 do Google ADS para E-commerce - Campanhas de PMax parte 1",
    sinopse: "Fundamentos e configura\u00e7\u00e3o inicial de campanhas Performance Max para e-commerce no Google.",
    link: "https://app.agenze.io/c/trilha-google-ads/sections/886672/lessons/3357949",
  },
  {
    trilha: "Trilha Google ADS",
    titulo: "80/20 do Google ADS para E-commerce - Campanhas de PMax parte 2",
    sinopse: "Otimiza\u00e7\u00e3o e estrat\u00e9gias intermedi\u00e1rias para escalar campanhas PMax no Google ADS.",
    link: "https://app.agenze.io/c/trilha-google-ads/sections/886672/lessons/3357950",
  },
  {
    trilha: "Trilha Google ADS",
    titulo: "80/20 do Google ADS para E-commerce - Campanhas de PMax parte 3",
    sinopse: "An\u00e1lise de dados e ajustes avan\u00e7ados em campanhas Performance Max de e-commerce.",
    link: "https://app.agenze.io/c/trilha-google-ads/sections/886672/lessons/3357955",
  },
  {
    trilha: "Trilha Google ADS",
    titulo: "80/20 do Google ADS para E-commerce - Campanhas de PMax parte 4",
    sinopse: "T\u00e1ticas avan\u00e7adas para maximizar o ROAS em campanhas PMax de lojas virtuais.",
    link: "https://app.agenze.io/c/trilha-google-ads/sections/886672/lessons/3357960",
  },
  {
    trilha: "Trilha Google ADS",
    titulo: "Setup Inicial de Configura\u00e7\u00e3o de Google ADS para E-commerce",
    sinopse: "Como criar e configurar do zero uma conta de Google ADS otimizada para e-commerce.",
    link: "https://app.agenze.io/c/trilha-google-ads/sections/886672/lessons/3357966",
  },
  {
    trilha: "Trilha Tr\u00e1fego para E-commerce",
    titulo: "4 Pilares do Sucesso do seu E-commerce na Black Friday",
    sinopse: "Estrat\u00e9gias essenciais de tr\u00e1fego para maximizar resultados de e-commerce na Black Friday.",
    link: "https://app.agenze.io/c/trilha-trafego-para-e-commerce/sections/886643/lessons/3357851",
  },
  {
    trilha: "Trilha Tr\u00e1fego para E-commerce",
    titulo: "An\u00e1lise Avan\u00e7ada de Dados para E-commerce",
    sinopse: "Como interpretar e usar dados avan\u00e7ados para otimizar campanhas de e-commerce.",
    link: "https://app.agenze.io/c/trilha-trafego-para-e-commerce/sections/886643/lessons/3357856",
  },
  {
    trilha: "Trilha Tr\u00e1fego para E-commerce",
    titulo: "CRM para E-commerce - Aumentando o LTV",
    sinopse: "Uso de CRM para aumentar o valor do tempo de vida do cliente em lojas virtuais.",
    link: "https://app.agenze.io/c/trilha-trafego-para-e-commerce/sections/886643/lessons/3357858",
  },
  {
    trilha: "Trilha Tr\u00e1fego para E-commerce",
    titulo: "Masterclass E-commerce do Zero \u00e0 Escala",
    sinopse: "Aula completa de estrat\u00e9gia de tr\u00e1fego para e-commerce do zero \u00e0 escala.",
    link: "https://app.agenze.io/c/trilha-trafego-para-e-commerce/sections/886643/lessons/3357860",
  },
  {
    trilha: "Trilha Tr\u00e1fego para E-commerce",
    titulo: "Trackeamento e Funil de Convers\u00e3o para E-commerce",
    sinopse: "Como rastrear o funil completo de convers\u00e3o e otimizar cada etapa no e-commerce.",
    link: "https://app.agenze.io/c/trilha-trafego-para-e-commerce/sections/886643/lessons/3357863",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "Aula 1",
    sinopse: "Introdu\u00e7\u00e3o \u00e0s automa\u00e7\u00f5es com n8n aplicadas \u00e0 rotina de gest\u00e3o de tr\u00e1fego pago.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3355557",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "Aula 2",
    sinopse: "Cria\u00e7\u00e3o dos primeiros fluxos de automa\u00e7\u00e3o para otimizar processos de tr\u00e1fego com n8n.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3357795",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "Domine o Fluxo de Vendas: Importando e Analisando o Template de Agente Aut\u00f4nomo para WhatsApp (n8n)",
    sinopse: "Como importar e usar o template de agente aut\u00f4nomo para WhatsApp no n8n.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3357800",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "Introdu\u00e7\u00e3o",
    sinopse: "Vis\u00e3o geral da trilha de automa\u00e7\u00f5es e das ferramentas que ser\u00e3o utilizadas no curso.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3357802",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "Monitor Autom\u00e1tico de Saldo do Meta Ads",
    sinopse: "Automa\u00e7\u00e3o para monitorar saldo de contas Meta ADS e enviar alertas autom\u00e1ticos.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3357806",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "Monitor de Campanhas Meta - WhatsApp",
    sinopse: "Automa\u00e7\u00e3o que envia resumo de performance de campanhas do Meta diretamente pelo WhatsApp.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3357809",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "Relat\u00f3rio Inteligente do Facebook Ads",
    sinopse: "Gera\u00e7\u00e3o autom\u00e1tica de relat\u00f3rios inteligentes com dados das campanhas do Facebook Ads.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3357811",
  },
  {
    trilha: "Trilha Automa\u00e7\u00f5es Aplicada \u00e0 Gest\u00e3o de Tr\u00e1fego",
    titulo: "IA e Automa\u00e7\u00f5es Pra aumentar seu lucro em at\u00e9 30x",
    sinopse: "Como combinar IA e automa\u00e7\u00f5es estrategicamente para multiplicar lucratividade em at\u00e9 30x.",
    link: "https://app.agenze.io/c/trilha-automacoes-aplicada-a-gestao-de-trafego/sections/886030/lessons/3511507",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Tudo Sobre o Pixel do Facebook",
    sinopse: "Guia completo sobre o Pixel do Meta: cria\u00e7\u00e3o, instala\u00e7\u00e3o, eventos e solu\u00e7\u00e3o de problemas.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3348182",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Funil e Objetivos de Campanha",
    sinopse: "Como escolher o objetivo correto e estruturar o funil de campanha no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3348190",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Funil de Pixel para Venda Direta",
    sinopse: "Configura\u00e7\u00e3o do funil de pixel otimizado para campanhas de venda direta no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3348199",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "An\u00fancios e Criativos",
    sinopse: "Como criar an\u00fancios e criativos de alta performance para campanhas no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3358283",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Como Configurar a API de Convers\u00f5es do Facebook",
    sinopse: "Configura\u00e7\u00e3o completa da API de Convers\u00f5es para melhorar rastreamento e otimiza\u00e7\u00e3o.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3348210",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Eventos Padr\u00f5es e Convers\u00f5es personalizadas",
    sinopse: "Como configurar eventos padr\u00f5es e criar convers\u00f5es personalizadas no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3358284",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Campanha Advantage+",
    sinopse: "Como usar campanhas Advantage+ para otimiza\u00e7\u00e3o autom\u00e1tica de p\u00fablico e criativos.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3358285",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Conjuntos de an\u00fancio",
    sinopse: "Configura\u00e7\u00e3o e otimiza\u00e7\u00e3o de conjuntos de an\u00fancios: p\u00fablico, or\u00e7amento e programa\u00e7\u00e3o.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3358307",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Introdu\u00e7\u00e3o \u00e0 API de Convers\u00f5es do Facebook",
    sinopse: "Conceito e vantagens da API de Convers\u00f5es em rela\u00e7\u00e3o ao Pixel do Facebook.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3358308",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Instalando a API de convers\u00e3o no Wordpress com plugin PYS",
    sinopse: "Tutorial de instala\u00e7\u00e3o da API de Convers\u00f5es via plugin PixelYourSite no WordPress.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883924/lessons/3358311",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Tipos de P\u00fablico Alvo - Personalizado (Quente)",
    sinopse: "Como criar e usar p\u00fablicos personalizados (quentes) para campanhas de remarketing.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883926/lessons/3348197",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Hierarquia e Exclus\u00e3o de P\u00fablicos para mais Resultado",
    sinopse: "Hierarquia de p\u00fablicos e uso de exclus\u00f5es para evitar sobreposi\u00e7\u00e3o e aumentar o ROI.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883926/lessons/3357664",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Tipos de P\u00fablico Alvo - Lookalike (Semelhante)",
    sinopse: "Cria\u00e7\u00e3o de p\u00fablicos semelhantes (lookalike) para prospectar novos clientes qualificados.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883926/lessons/3357711",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Tipos de P\u00fablico Alvo - Interesse (ou P\u00fablicos Salvo)",
    sinopse: "Segmenta\u00e7\u00e3o por interesses para alcan\u00e7ar p\u00fablicos frios e testar novas audi\u00eancias.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/883926/lessons/3357731",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "An\u00e1lise de M\u00e9tricas, Otimiza\u00e7\u00e3o e Cria\u00e7\u00e3o de Campanha na Pr\u00e1tica",
    sinopse: "Processo completo de cria\u00e7\u00e3o, an\u00e1lise e otimiza\u00e7\u00e3o de campanhas baseado em dados reais.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357748",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Checklist, Alinhamento, Estrat\u00e9gia e Campanha para qualquer Black Friday",
    sinopse: "Planejamento estrat\u00e9gico completo para campanhas de Black Friday de alto desempenho.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357753",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Estrat\u00e9gia do Remarketing Estratificado",
    sinopse: "M\u00e9todo avan\u00e7ado de remarketing por camadas para converter leads com mais precis\u00e3o.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357758",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "FLUXO DE DECIS\u00d5ES DO RALO AO ROI NO TALO",
    sinopse: "Framework de decis\u00e3o para identificar gargalos e maximizar ROI em campanhas de tr\u00e1fego.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357762",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "3 Pilares do Sucesso do Tr\u00e1fego",
    sinopse: "Os tr\u00eas fundamentos que determinam o sucesso de qualquer estrat\u00e9gia de tr\u00e1fego pago.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357765",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Configurando um Cat\u00e1logo de Produtos",
    sinopse: "Como criar e configurar cat\u00e1logo de produtos para campanhas din\u00e2micas no Meta ADS.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357767",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Estruturas de Campanha que geraram mais de 200 milh\u00f5es de reais em vendas on-line",
    sinopse: "Estruturas de campanha comprovadas que geraram mais de R$200M em vendas online.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357776",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Como calcular o ROI breakeven pra seu Cliente ou para seu neg\u00f3cio",
    sinopse: "Como calcular o ROI de equil\u00edbrio (breakeven) para definir metas realistas de campanha.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357781",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Metodologia FOCA (Funil de Objetivos de Campanha)",
    sinopse: "A metodologia FOCA para estruturar campanhas com base no funil de objetivos.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357790",
  },
  {
    trilha: "Trilha Meta ADS",
    titulo: "Envio de Relat\u00f3rio e Feedback ao seu Cliente",
    sinopse: "Como criar e enviar relat\u00f3rios profissionais de performance de campanhas para clientes.",
    link: "https://app.agenze.io/c/trilha-meta-ads/sections/886029/lessons/3357791",
  },
  {
    trilha: "Trilha Vivendo de Tr\u00e1fego",
    titulo: "O Melhor Caminho pra Come\u00e7ar no Mercado Digital",
    sinopse: "Orienta\u00e7\u00e3o estrat\u00e9gica sobre o melhor caminho para iniciar no mercado digital.",
    link: "https://app.agenze.io/c/trilha-de-conteudo/sections/882146/lessons/3343351",
  },
  {
    trilha: "Trilha Vivendo de Tr\u00e1fego",
    titulo: "Conquistando meu Primeiro Cliente",
    sinopse: "Estrat\u00e9gias e abordagens pr\u00e1ticas para fechar o primeiro cliente de gest\u00e3o de tr\u00e1fego.",
    link: "https://app.agenze.io/c/trilha-de-conteudo/sections/882146/lessons/3343374",
  },
  {
    trilha: "Trilha Vivendo de Tr\u00e1fego",
    titulo: "90 Clientes com apenas 4 Pessoas na opera\u00e7\u00e3o",
    sinopse: "Como estruturar uma opera\u00e7\u00e3o enxuta e escal\u00e1vel para atender 90 clientes com 4 pessoas.",
    link: "https://app.agenze.io/c/trilha-de-conteudo/sections/882146/lessons/3503832",
  },
  {
    trilha: "Trilha Vivendo de Tr\u00e1fego",
    titulo: "O In\u00edcio da Gest\u00e3o de Tr\u00e1fego como Presta\u00e7\u00e3o de Servi\u00e7o",
    sinopse: "Fundamentos essenciais para come\u00e7ar como prestador de servi\u00e7os de tr\u00e1fego pago.",
    link: "https://app.agenze.io/c/trilha-de-conteudo/sections/882146/lessons/3341343",
  },
  {
    trilha: "Trilha Vivendo de Tr\u00e1fego",
    titulo: "Alinhamento Estrat\u00e9gico: O segredo do sucesso",
    sinopse: "Como alinhar estrat\u00e9gia com cliente e equipe para garantir resultados consistentes.",
    link: "https://app.agenze.io/c/trilha-de-conteudo/sections/882146/lessons/3343173",
  },
  {
    trilha: "Trilha Vivendo de Tr\u00e1fego",
    titulo: "Passos Essenciais P\u00f3s Fechamento de Contrato",
    sinopse: "O que fazer imediatamente ap\u00f3s fechar um contrato para iniciar bem o relacionamento.",
    link: "https://app.agenze.io/c/trilha-de-conteudo/sections/882146/lessons/3343371",
  },
  {
    trilha: "Trilha Vivendo de Tr\u00e1fego",
    titulo: "Descobrindo o ROI Breakeven do Cliente",
    sinopse: "Como calcular e comunicar ao cliente o ROI de equil\u00edbrio das campanhas de tr\u00e1fego.",
    link: "https://app.agenze.io/c/trilha-de-conteudo/sections/882146/lessons/3343377",
  },
]
